scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 2

  BorderZero:
    enabled: true
    convention: zero # or `none`

  # Unfortunately does not compare with our palColor/emoColor functions
  ColorKeyword:
    enabled: false

  # Unfortunately does not compare with our palColor/emoColor functions
  ColorVariable:
    enabled: false

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: false

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: new_line # or 'same_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: camel_case # or 'hyphenated_lowercase', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 6
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: false

  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 20

  PropertySortOrder:
    enabled: true
    order:
      - content
      - quotes
      -
      - display
      - visibility
      -
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      -
      - box-sizing
      -
      - grid
      - grid-after
      - grid-area
      - grid-auto-columns
      - grid-auto-flow
      - grid-auto-rows
      - grid-before
      - grid-start
      - grid-end
      - grid-gap
      - grid-column
      - grid-column-start
      - grid-column-end
      - grid-column-gap
      - grid-columns
      - grid-row
      - grid-row-start
      - grid-row-end
      - grid-row-gap
      - grid-rows
      - grid-template
      - grid-template-areas
      - grid-template-columns
      - grid-template-rows
      -
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - align-content
      - align-items
      - align-self
      - justify-content
      - order
      -
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      -
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      -
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      -
      -  float
      - clear
      -
      - overflow
      - overflow-x
      - overflow-y
      -
      - clip
      - zoom
      -
      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width
      -
      - table-layout
      - empty-cells
      - caption-side
      - border-spacing
      - border-collapse
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      -
      - transform
      - transform-origin
      - transform-style
      - backface-visibility
      - perspective
      - perspective-origin
      -
      - transition
      - transition-property
      - transition-duration
      - transition-timing-function
      - transition-delay
      -
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      -
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      -
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      -
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      -
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      -
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      -
      - stroke-width
      - stroke-linecap
      - stroke-dasharray
      - stroke-dashoffset
      - stroke
      -
      - opacity
      -
      - background
      - background-color
      - background-image
      - background-repeat
      - background-position
      - background-size
      - box-shadow
      - fill
      -
      - color
      -
      - font
      - font-family
      - font-size
      - font-size-adjust
      - font-stretch
      - font-effect
      - font-style
      - font-variant
      - font-weight
      -
      - font-emphasize
      - font-emphasize-position
      - font-emphasize-style
      -
      - letter-spacing
      - line-height
      - list-style
      - word-spacing
      -
      - text-align
      - text-align-last
      - text-decoration
      - text-indent
      - text-justify
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-rendering
      - text-outline
      - text-shadow
      - text-transform
      - text-wrap
      - word-wrap
      - word-break
      -
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-style
      - text-emphasis-position
      -
      - vertical-align
      - white-space
      - word-spacing
      - hyphens
      -
      - src
      -
      - tab-size
      - counter-reset
      - counter-increment
      - resize
      - cursor
      - pointer-events
      - speak
      - user-select
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - caret-color
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax', 'fr',        # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  QualifyingElement:
    enabled: false
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 5

  SelectorFormat:
    enabled: false
    convention: strict_BEM # or 'hyphenated_lowercase', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterPropertyColon:
    enabled: true
    style: at_least_one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes # or single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties:
    - font

  VendorPrefix:
    enabled: false
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
